apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  name: main-rules-alert-config
  namespace: monitoring
spec:
  route:
    receiver: 'email' #send email for both custom alerts.
    repeatInterval: 30m #resend email if issue persists after 30 mins and keep repeating until fixed.
    routes:
    - matchers:
      - name: alertname
        value: HostHighCpuLoad
    - matchers:
      - name: alertname
        value: KubernetesPodCrashLooping
      repeatInterval: 10m #Override above value with 10m
  receivers:
  - name: 'email'
    emailConfigs:
    - to: 'email@example.come'
      from: 'email@example.come'
      smarthost: 'smtp.gmail.com:587'
      authUsername: 'email@example.come'
      authIdentity: 'email@example.come'
      authPassword:
       name: gmail-auth #use https://myaccount.google.com/lesssecureapps OR app-password if 2FA enabled. 
       key: password