apiVersion: v1
kind: Secret
type: Opaque
metadata: 
  name: gmail-auth
  namespace: monitoring #same as Alermanager config file. 
data:
  password: <base64 encoded password>
  #use https://myaccount.google.com/lesssecureapps OR app-password (https://myaccount.google.com/apppasswords) if 2FA enabled. 