serviceMonitor:
  enabled: true
  labels:
    release: monitoring #name of Promethus release deployed via helm

redisAddress: redis://redis-cart:6379 #redis servcie name or endpoint
#redisAddress: localhost:6379 #redis servcie name or endpoint